---
name: warmi
version: 1.0.0+13
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  dio: ^4.0.0
  #  data_connection_checker: ^0.3.4
  recase: ^4.0.0
  api_cache_manager: ^1.0.2
  line_icons: ^2.0.1
  url_launcher: ^6.0.9
  permission_handler: ^8.1.4+2
  in_app_update: ^2.0.0
  whatsapp_unilink: ^2.0.0
  responsive_sizer: ^3.0.4+4
  google_fonts: ^2.1.0
  google_mobile_ads: ^0.13.5
  get_storage: ^2.0.3
  intl: ^0.17.0
  lint: ^1.7.2
  carousel_slider: ^4.0.0
  custom_navigation_bar: ^0.8.2
  flutter_iconly: ^1.0.2
  flutter_statusbarcolor_ns: ^0.4.0
  cached_network_image: ^3.1.0
  image_picker: ^0.8.2
  external_path: ^1.0.1
  dotted_decoration: ^2.0.0
  esc_pos_bluetooth: ^0.4.1
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  print_bluetooth_thermal: ^1.0.2
  image: ^3.0.8
  clipboard: ^0.1.3
  device_info_plus: ^3.1.0
  package_info: ^2.0.2
  flutter_barcode_scanner: ^2.0.0
  #  image_downloader: ^0.30.0
  #  screenshot: ^1.2.3
  equatable: ^2.0.3
  share_plus: ^3.0.4
  get: ^4.3.8
  badges: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/d-post.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

# remove package data_connection_checker
# package in_app_update only android
# package external_path only android
# package print_bluetooth_thermal only android
# package flutter_barcode_scanner minimum deployment target to 12
#      <string>ca-app-pub-4602657974905060~9816958967</string>

